variables:
    SolutionBaseName: 'DFC.Api.Location'
    ArmTemplateRoot: "$(System.DefaultWorkingDirectory)/Resources/ArmTemplates"
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.11.2
    endpoint: 'GitHub (ESFA)'

pool:
  name: NCS - CI and CD
  demands:
  - msbuild
  - visualstudio

trigger: 
  branches:
    include: 
    - dev
    - master

pr:
  branches:
    include: 
    - dev
    - master

stages:
- stage: Build
  displayName: Build, Test and Analyze
  jobs:
  - job: TestArmTemplates
    displayName: "Test ARM Templates"
    steps:
    - template: /AzureDevOpsTemplates/Build/StepTemplates/dfc-arm-build.yml@dfc-devops
      parameters:
        ArmTemplateRoot: '${{ variables.ArmTemplateRoot }}'
        SolutionBaseName: '${{ variables.SolutionBaseName }}'

  - job: BuildTestAndAnalyze
    displayName: "Build and test application"
    steps:
    - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcore-build-sonar.yml@dfc-devops
      parameters:
        SolutionBaseName: $(SolutionBaseName)
        BuildPlatform: $(BuildPlatform)
        BuildConfiguration: $(BuildConfiguration)
        DotNetCoreVersion: '3.1.100'
        PublishWebApp: true
        TestSuffix: UnitTests

- stage: DeployToLabApiLocation
  condition: succeeded()
  displayName: Deploy to LAB_ApiLocation
  variables:
  - template: VariableTemplates/LabEnvironmentVariables.yml
  - group: dfc-shared-lab
  - group: dfc-app-shared-all
  - group: dfc-app-shared-lab
  - group: 'KeyVault - dfc-lab-shared-kv'
  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: '$(ResourceGroup)'
      PackageFile:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.DeploymentPackages/${{ variables.SolutionBaseName }}.zip"
      ArmTemplateFolder: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ArmTemplates/"
      FunctionAppDomain: '$(FunctionAppDomain)'
      EnvironmentName: LAB_ApiLocation
      DFCAzureDevOpsProjectGuid: $(DFCAzureDevOpsProjectGuid)
      ApimLoggerName: "$(ApimLoggerName)"
      ApimProductName: "$(ApimProductName)"
      SharedResourceGroup: "$(SharedResourceGroup)"
      ApimServiceName: "$(ApimServiceName)"
      ApimApiName: $(ApimApiName)
      Apis:
        -
          - azureFunctionName: '${{ variables.WebAppPrefix }}-api-location-fa'

- stage: DeployToDevApiLocation
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
  displayName: Deploy to DEV_ApiLocation
  variables:
  - template: VariableTemplates/DevEnvironmentVariables.yml
  - group: dfc-shared-dev
  - group: dfc-app-shared-all
  - group: dfc-app-shared-dev
  - group: 'KeyVault - dfc-dev-shared-kv'
  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: '$(ResourceGroup)'
      PackageFile:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.DeploymentPackages/${{ variables.SolutionBaseName }}.zip"
      ArmTemplateFolder: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ArmTemplates/"
      FunctionAppDomain: '$(FunctionAppDomain)'
      EnvironmentName: DEV_ApiLocation
      DFCAzureDevOpsProjectGuid: $(DFCAzureDevOpsProjectGuid)
      ApimLoggerName: "$(ApimLoggerName)"
      ApimProductName: "$(ApimProductName)"
      SharedResourceGroup: "$(SharedResourceGroup)"
      ApimServiceName: "$(ApimServiceName)"
      ApimApiName: $(ApimApiName)
      Apis:
        -
          - azureFunctionName: '${{ variables.WebAppPrefix }}-api-location-fa'

- stage: DeployToSitApiLocation
  condition: succeeded()
  displayName: Deploy to SIT_ApiLocation
  variables:
  - template: VariableTemplates/SitEnvironmentVariables.yml
  - group: dfc-shared-sit
  - group: dfc-app-shared-all
  - group: dfc-app-shared-sit
  - group: 'KeyVault - dfc-sit-shared-kv'
  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-CDH-Dev/Test (962cae10-2950-412a-93e3-d8ae92b17896)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: '$(ResourceGroup)'
      PackageFile:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.DeploymentPackages/${{ variables.SolutionBaseName }}.zip"
      ArmTemplateFolder: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ArmTemplates/"
      FunctionAppDomain: '$(FunctionAppDomain)'
      EnvironmentName: SIT_ApiLocation
      DFCAzureDevOpsProjectGuid: $(DFCAzureDevOpsProjectGuid)
      ApimLoggerName: "$(ApimLoggerName)"
      ApimProductName: "$(ApimProductName)"
      SharedResourceGroup: "$(SharedResourceGroup)"
      ApimServiceName: "$(ApimServiceName)"
      ApimApiName: $(ApimApiName)
      Apis:
        -
          - azureFunctionName: '${{ variables.WebAppPrefix }}-api-location-fa'

- stage: DeployToPPApiLocation
  condition: and(eq(dependencies.Build.result,'Succeeded'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: Deploy to PP_ApiLocation
  variables:
  - group: dfc-shared-pp
  - group: dfc-app-shared-all
  - group: dfc-app-shared-pp
  - group: 'KeyVault - dfc-pp-shared-kv'
  - template: VariableTemplates/PPEnvironmentVariables.yml
  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-DIG-PreProd (931bc9f6-359c-4f65-a753-1ee191a1fd6c)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: '$(ResourceGroup)'
      PackageFile:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.DeploymentPackages/${{ variables.SolutionBaseName }}.zip"
      ArmTemplateFolder: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ArmTemplates/"
      FunctionAppDomain: '$(FunctionAppDomain)'
      EnvironmentName: PP_ApiLocation
      DFCAzureDevOpsProjectGuid: $(DFCAzureDevOpsProjectGuid)
      ApimLoggerName: "$(ApimLoggerName)"
      ApimProductName: "$(ApimProductName)"
      SharedResourceGroup: "$(SharedResourceGroup)"
      ApimServiceName: "$(ApimServiceName)"
      ApimApiName: $(ApimApiName)
      Apis:
        -
          - azureFunctionName: '${{ variables.WebAppPrefix }}-api-location-fa'

- stage: DeployToPRDApiLocation
  condition: and(eq(dependencies.DeployToPPApiLocation.result,'Succeeded'), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: Deploy to PRD_ApiLocation
  variables:
  - group: dfc-shared-prd
  - group: dfc-app-shared-all
  - group: dfc-app-shared-prd
  - group: 'KeyVault - dfc-prd-shared-kv'
  - template: VariableTemplates/PRDEnvironmentVariables.yml
  jobs:
  - template: JobTemplates/deploy-environment.yml
    parameters:
      AzureSubscription: 'SFA-DIG-Prod (6c93f7dc-6c36-4ea6-8de3-3f4574f88027)'
      EnvironmentTag: '$(EnvironmentTag)'
      ParentBusiness: '$(ParentBusiness)'
      ServiceOffering: '$(ServiceOffering)'
      ResourceGroup: '$(ResourceGroup)'
      PackageFile:  "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.DeploymentPackages/${{ variables.SolutionBaseName }}.zip"
      ArmTemplateFolder: "$(Pipeline.Workspace)/${{ variables.SolutionBaseName }}.Resources.ArmTemplates/"
      FunctionAppDomain: '$(FunctionAppDomain)'
      EnvironmentName: PRD_ApiLocation
      DFCAzureDevOpsProjectGuid: $(DFCAzureDevOpsProjectGuid)
      ApimLoggerName: "$(ApimLoggerName)"
      ApimProductName: "$(ApimProductName)"
      SharedResourceGroup: "$(SharedResourceGroup)"
      ApimServiceName: "$(ApimServiceName)"
      ApimApiName: $(ApimApiName)
      Apis:
        -
          - azureFunctionName: '${{ variables.WebAppPrefix }}-api-location-fa'
