parameters:
  AzureSubscription: ''
  SetEsfaResourceGroupTagsScript: 'https://raw.githubusercontent.com/SkillsFundingAgency/dfc-devops/master/PSScripts/Set-EsfaResourceGroupTags.ps1'
  PackageFile:  ''
  ArmTemplateFolder: ''
  Location: 'West Europe'
  ArmOutputVariableName: 'ARMOutputs'
  EnvironmentTag: 'DEV/Test'
  ParentBusiness: ''
  ServiceOffering: ''
  ResourceGroup: ''
  FunctionAppDomain: ''
  EnvironmentName: ''
  DFCAzureDevOpsProjectGuid: ''
  DfcContentTestsBuildId: ''
  SharedResourceGroup: ''
  ApimServiceName: ''
  ApimProductName: ''
  ApimApiName: ''
  Apis: []

jobs:
- deployment: DeployTemplate
  displayName: "Deploy arm templates"
  environment: ${{ parameters.EnvironmentName }}
  strategy:
    runOnce:
      deploy:
        steps:
        - template: ../StepTemplates/deploy-arm-template.yml
          parameters: 
            AzureSubscription: '${{ parameters.AzureSubscription }}'
            SetEsfaResourceGroupTagsScript: '${{ parameters.SetEsfaResourceGroupTagsScript }}'
            EnvironmentTag: '${{ parameters.EnvironmentTag }}'
            ParentBusiness: '${{ parameters.ParentBusiness }}'
            ServiceOffering: '${{ parameters.ServiceOffering }}'
            ResourceGroup: '${{ parameters.ResourceGroup }}'
            Location: '${{ parameters.Location }}'
            ArmOutputVariableName: '${{ parameters.ArmOutputVariableName }}'
            ArmTemplateFolder: '${{ parameters.ArmTemplateFolder }}'

- ${{ each apiPartition in parameters.Apis }}:
  - ${{ each api in apiPartition }}:
    - deployment: Deploy${{ api.name }}
      displayName: "Deploy ${{ api.name }}"
      environment: ${{ parameters.EnvironmentName }}
      dependsOn: 
      - DeployTemplate
      strategy:
        runOnce:
          deploy:
            steps:
            - template: ../StepTemplates/deploy-functionapp-apim-zdt.yml
              parameters:
                WebAppName: '${{ api.azureFunctionName }}'
                AzureSubscription: '${{ parameters.AzureSubscription }}'
                FunctionAppDomain: '${{ parameters.FunctionAppDomain }}'
                PackageFile: '${{ parameters.PackageFile }}'
                ResourceGroup: '${{ parameters.ResourceGroup }}'
                SharedResourceGroup: '${{ parameters.SharedResourceGroup }}'
                ApimServiceName: '${{ parameters.ApimServiceName }}'
                APIMProductName: '${{ parameters.ApimProductName }}'
                APIMApiName: '${{ parameters.ApimApiName }}'