variables:
- name: aspInstances
  value: 2
- name: aspSize
  value: 2
- name: aspTier
  value: Standard
- name: ExceptionCountThreshold
  value: 10
- name: MemoryPercentageThreshold
  value: 75
- name: CPUPercentageThreshold
  value: 75
- name: EnableAzureMonitorAlerting
  value: true
- name: ReleaseEnvironmentName
  value: lab
- name: WebAppPrefix
  value: dfc-lab
- name: FunctionAppInsightName
  value: $(WebAppPrefix)-api-location-ai
- name: FunctionAppName
  value: $(WebAppPrefix)-api-location-fa
- name: ResourceGroup
  value: $(WebAppPrefix)-api-location-rg
- name: appServicePlanName
  value: $(WebAppPrefix)-api-location-asp
- name: apimLoggerName
  value: LocationServices-logger
- name: apimProductName
  value: LocationServices
- name: apimApiName
  value: Location