variables:
- name: aspInstances
  value: 2
- name: aspSize
  value: 2
- name: aspTier
  value: Standard
- name: ExceptionCountThreshold
  value: 10
- name: MemoryPercentageThreshold
  value: 75
- name: CPUPercentageThreshold
  value: 75
- name: EnableAzureMonitorAlerting
  value: true
- name: ReleaseEnvironmentName
  value: sit
- name: WebAppPrefix
  value: dfc-sit
- name: FunctionAppInsightName
  value: $(WebAppPrefix)-api-location-ai
- name: FunctionAppName
  value: $(WebAppPrefix)-api-location-fa
- name: ResourceGroup
  value: $(WebAppPrefix)-api-location-rg
- name: appServicePlanName
  value: $(WebAppPrefix)-api-location-asp
- name: apimLoggerName
  value: $(ApimLoggerName)
- name: apimProductName
  value: $(ApimProductInstanceName)
- name: apimApiName
  value: Location